name: Deploy of stagging 

on:
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: windows-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install
