name: Deploy of staging 

on:
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: windows-latest

    steps:
      - name: Login to Azure
        uses: hyperskill/azure-login@v3.0.0
        with:
          # Azure client id
          client_id: 29ab9778-9223-4c2e-92f4-37a6ce20eaf3
          # Azure client secret
          client_secret: lun8Q~oWlb07OTCVlmQwuJslXmp6-GQGBWXn1a5q
          # Azure subscription id
          subscription_id: 06fddf6b-1702-4b31-ac73-942642d910e0
          # Azure tenant id
          tenant_id: b3236d99-9c3f-40e6-ae82-44c921c09e05

